# Generated by Django 4.2.1 on 2023-07-23 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prereg_name', models.CharField(max_length=30)),
                ('prereg_email', models.EmailField(max_length=254)),
                ('prereg_mob', models.CharField(max_length=15)),
                ('districtd', models.PositiveIntegerField(choices=[(1, 'Choice 1'), (2, 'Choice 2')])),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtd', models.PositiveIntegerField(choices=[(1, 'Thiruvananthapuram'), (2, 'Kollam'), (3, 'Pathanamthitta'), (4, 'Alappuzha'), (5, 'Kottayam'), (6, 'Idukki'), (7, 'Ernakulam'), (8, 'Thrissur'), (9, 'Palakkad'), (10, 'Malappuram'), (11, 'Kozhikode'), (12, 'Wayanad'), (13, 'Kannur'), (14, 'Kasaragod')])),
                ('ideator_mobile', models.CharField(max_length=12)),
                ('ideator_gender', models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('ideator_dob', models.DateField()),
                ('combinedInstitution', models.CharField(max_length=70)),
                ('ideator_cat', models.PositiveIntegerField(choices=[(4, 'Category 4'), (5, 'Category 5')])),
                ('ideator_year', models.PositiveIntegerField(choices=[(6, 'Year 6'), (7, 'Year 7')])),
                ('ideator_dep', models.CharField(max_length=70)),
                ('type_identity_no', models.CharField(max_length=70)),
                ('btnval', models.IntegerField()),
                ('Ideator_name', models.CharField(max_length=100, null=True)),
                ('cas_cat', models.CharField(max_length=50)),
                ('bank_acno', models.CharField(blank=True, max_length=50, null=True)),
                ('repeat_bank_acno', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
